var colors = ["#ff0000","#334455"];//the color sets of the triangles
var width = screen.width;
var cout = 0;
var height = screen.height;
var rectWidth = Math.round(Math.random()*150)+50;
var rectHeight = 20;
var wallHeight = 10;
var speed = 56;// the speed of the rectangles towards left.
var gap = 50;// the gap between two rectangles
var radius = 20;
var speedBallDown = 250;
var speedBallUp = 200;
var speedBallRight = 20;
var bounceHeight = height / 12;
var wallStartY = 0;
var triangleHeight = 30;
var triangleWidth = 15;
/*var colors = ["#ff0000","#334455"];//the color sets of the triangles
var width = screen.width;
var height = screen.height;
var rectWidth = Math.round(Math.random()*50)+30;
var rectHeight = 20;
var wallHeight = 20;
var speed = 50;// the speed of the rectangles towards left.
var gap = 60;// the gap between two rectangles
var radius = 15;
var speedBallDown = 150;
var speedBallUp = 150;
var speedBallRight = 20;
var bounceHeight = width / 14;
var wallStartY = 0;
var triangleHeight = 20;
var triangleWidth = 15;*/